import turtle

screen = turtle.Screen()  
my_turtle = turtle.Turtle()
my_turtle.shape("turtle")
my_turtle.forward(50)
my_turtle.right(45)
my_turtle.forward(50)
my_turtle.right(45)
my_turtle.forward(50)
my_turtle.right(45)
my_turtle.forward(50)
my_turtle.right(45)
my_turtle.forward(50)
my_turtle.right(45)
my_turtle.forward(50)
my_turtle.right(45)
my_turtle.forward(50)
my_turtle.right(45)
my_turtle.forward(50)
screen.mainloop()
